dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: T8vlXtLN5nmfHbMCYvzTif+uRmFAybsY9ejt6EapwNwYObJTs39LkAKzGj17+kMJ/PvdM/ZdvNUxvQ6Le3s9Q4xmTjLokoQXkEir++PB4Z6DlwncoJCYfqAiUHiPUoiAO0ulShVAmlnRa2F6WAuCUQeeweLpjqIwHPdgLbNWsLS7XRnS3XNZKneLlWkdYGsoLPD9HDkfc/cANLVLXf6wu0+RxL+FFFjmBbUEKK5tVudZcB/oTP9eoXTzuM2xxwQby6JxXQJhANbzX2/URJPDiBKssGFP/XA4bmcxHCEWeSxpGvEARiQ8B2Rik+2LZux05Tybu4J32WU7S+ioMaFmi4XoVddvQfxkOm73JYSxS3XZhxy/Vl7c/RiZDbX3LVLWuwQ1FKBc4O17pz8i3av3TLivQOY8N1nEvFM9LEo1bWq42zUPNfSESw7qMrBWfLejnbWNYPRgQIUvVrXOv7oyq37TeoD+UVeU4PTHSIcgmjAd3RsNTLG67GcqEWqvr3jMmJ725TFOEJkpOfzwXhTvBI2wQu+Tf+lhc6wMFaMgNT9V8caF0GNvG1osmM/iJVApRmiGV0hsJ1jKr12KUpziIo71WLrjW6zei6t2/5KEljdav21f55MNTgO9wtpNEZordlJVj1Gh4x0E4BKpJZjlF12Hzuoyk1c0RRFgadhSYZc=
  file: Gerbers/PIN-107_gerbers.zip
  on:
    repo: w4xzr/PIN-107
  skip_cleanup: 'true'
